### ISSUE TITLE
disable forcing dashes on win32

### ISSUE THREAD

**Issue by devmondo** [jcarpanelli/spinnies#1]
Hi, 
really awesome spinner and options, thanks alot for it :)

but can you please disable the enforcement of dashes spinners on win32, i am using windows 10 and it is perfectly capable of showing all symbols, i tested by manually commenting the if condition and it wokred.

thanks in advace :)

**Comment by jcarpanelli** [comment]
Hello, @devmondo! Thanks for raising this :muscle: . I wasn't 100% sure whether it was necessary to use a more conventional set of symbols for `win32`. I'm glad that it's not! I will fix it soon and release a new version afterwards. In the meantime, you can set the spinner animation manually as explained [here](https://github.com/jcarpanelli/spinnies#new-spinniesoptions) (example included!).

**Comment by devmondo** [comment]
thank @jcarpanelli for the prompt reply, but unless i am doing something wrong, the override option you mention i tried but it does not seem to work!

**Comment by jcarpanelli** [comment]
Hello, there, @devmondo ! I finally kept the `win32` validation, but thanks to this issue I realized that it wasn't possible to override the default `win32` spinner, which was a bug :bug:.
I released `v.0.3.1` with a fix. You now should be able to override the `spinner` option as explained in the example mentioned in my previous answer! If you think your issue has been solved, please feel free to close this issue.

**Comment by devmondo** [comment]
awesome work man!!!, it works perfectly, really loves your work there :)
